### ISSUE TITLE
17_Project - should be getting an error 

### ISSUE THREAD

**Issue by sociologyquinn** [dlab-berkeley/Python-Fundamentals-Legacy#80]
1.2 Load in multiple files: why don't we get an error when print(__) is run without making the appropriate changes? It prints a bunch of output without needing to change to "print(file)"

**Comment by emilygrabowski** [comment]
This isn't an error, but _ and __ are magic variables referring to previous cell results. I extended the _______ so that it doesn't line up with any of the magic variables (which will be coming up in the next PR). We should also revisit the use of ___ in these partially-complete cells because of the possibility of confusion.
